[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "chromedriver-autoinstaller>=0.6.4",
    "requests>=2.32.4",
    "selenium>=4.34.0",
]
